<?php


return [
    'city' => 't',
    'NuRecords' => '500', // number of orders to show
    'warehouseId' => 1,
    'access'=>[
        'usersEdit' => 'ویرایش اطلاعات و دسترسی کاربران',
        'addOrder' => 'ثبت سفارش',
        'refund' => 'ثبت سفارش بازگشت به انبار',
        'changeOrderState' =>'تغییر وضعیت سفارش به ارسال شده',
        'showAllOrders' => 'مشاهده و ویرایش همه سفارشات',
        'changeDiscount' => 'تغییر تخفیف هنگام ثبت سفارش',
        'changePrice' => 'تغییر قیمت هنگام ثبت سفارش',
        'sellRawProduct' => 'فروش محصولات از دسته ماده اولیه',
        'allCustomers' => 'مشاهده و ویرایش اطلاعات همه مشتربان',
        'counter' => 'حسابداری',
        'statistic' => 'مشاهده آمار',
        'warehouse' => 'انبار داری',
        'manageSafir' => 'کنترل امور سفیران',
        'workReport' => 'گزارش کار نمایندگی ها',
        'addWithdrawal' => 'افزودن درخواست واریز',
        'confirmWithdrawal' => 'تایید درخواست واریز',
        'payWithdrawal' => 'پرداخت درخواست واریز',
    ],
    'usersEdit' => false,
    'addOrder' => false,
    'refund'=> false,
    'changeOrderState' =>false,
    'showAllOrders' => false,
    'changeDiscount' => false,
    'changePrice' => false,
    'sellRawProduct' => false,
    'allCustomers' => false,
    'counter' => false,
    'statistic' => false,
    'warehouse' => false,
    'manageSafir' => false,
    'workReport' => false,
];
