<?php

return [
    'city' => 't',
    'NuRecords' => '500', // number of orders to show
    'warehouseId' => 1,
    'discount' => 0,
    'access'=>[
        'usersEdit' => 'ویرایش اطلاعات و دسترسی کاربران',
        'addOrder' => 'ثبت سفارش',
        'refund' => 'ثبت سفارش بازگشت به انبار',
        'changeOrderState' =>'تغییر وضعیت سفارش به ارسال شده',
        'showAllOrders' => 'مشاهده همه سفارشات',
        'editAllOrders' => 'ویرایش همه سفارشات',
        'changeDiscount' => 'تغییر تخفیف هنگام ثبت سفارش',
        'changePrice' => 'تغییر قیمت هنگام ثبت سفارش',
        'sellRawProduct' => 'فروش محصولات از دسته ماده اولیه',
        'warehouseTransfer' => 'انتقال بین انبارها',
        'allCustomers' => 'مشاهده اطلاعات همه مشتربان',
        'editAllCustomers' => 'ویرایش اطلاعات همه مشتربان',
        'blockList' => 'مسدود کردن دسترسی مشتریان',
        'counter' => 'حسابداری',
        'cheque' => 'مدیریت چک ها',
        'statistic' => 'مشاهده آمار',
        'warehouse' => 'مشاهده اطلاعات انبار',
        'formulation' => 'مشاهده و ویرایش فرمولاسیون',
        'editWarehouse' => 'ویرایش اطلاعات انبار',
        'manageSafir' => 'کنترل امور سفیران',
        'addWorkReport' => 'ثبت گزارش کار',
        'workReport' => 'مشاهده گزارش کار همه',
        'withdrawal' => 'افزودن درخواست واریز',
        'withdrawalPay' => 'ثبت رسید پرداخت درخواست واریز',
        'withdrawalRecipient' => 'ثبت دریافت کالا و خدمات بعد از واریز',
        'allWithdrawal' => 'مشاهده همه درخواستهای واریز',
    ],
];
